defaults: &defaults
  machine: true
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.21
    TERRATEST_LOG_PARSER_VERSION: v0.13.13
    MODULE_CI_VERSION: v0.13.3
    TERRAFORM_VERSION: 0.11.13
    TERRAGRUNT_VERSION: NONE
    PACKER_VERSION: 1.3.2
    GOLANG_VERSION: 1.11.2

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    configure-environment-for-gruntwork-module \
      --circle-ci-2 \
      --circle-ci-2-machine-executor \
      --terraform-version ${TERRAFORM_VERSION} \
      --terragrunt-version ${TERRAGRUNT_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --use-go-dep \
      --go-version ${GOLANG_VERSION} \
      --go-src-path test

version: 2.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - run:
          name: create log directory
          command: mkdir -p /tmp/logs

      - run:
          name: run tests
          command: run-go-tests --path test --timeout 1h --circle-ci-2 | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always

      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

  release:
    <<: *defaults
    steps:
      - checkout

      # The weird way you have to set PATH in Circle 2.0
      - run: echo 'export PATH=$HOME/.local/bin:$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-ubuntu"
      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-amazon-linux"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - test
          # Publish new AMIs whenever a new vesion (e.g., v0.3.4) is released
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
