defaults: &defaults
  working_directory: /home/circleci/.go_workspace/src/github.com/gruntwork-io/terraform-aws-influx
  machine:
    image: circleci/classic:201711-01
#  docker:
#    - image: circleci/golang:1.10

version: 2.0
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: &install_gruntwork_tooling
          name: install gruntwork tooling
          command: |
            sudo apt-get -y update
            curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.21
            gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "v0.13.3"
            configure-environment-for-gruntwork-module --circle-ci-2 --use-go-dep --go-src-path test

      - run:
          name: install terratest log parser
          command: |
            gruntwork-install --binary-name 'terratest_log_parser' --repo 'https://github.com/gruntwork-io/terratest' --tag 'v0.13.8'

      - run:
          name: create log directory
          command: mkdir -p /tmp/logs

      - run:
          name: run tests
          command: run-go-tests --path test --timeout 1h --circle-ci-2 | tee /tmp/logs/all.log
          no_output_timeout: 3600s

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always

      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

  release:
    machine: true
    steps:
      - checkout

      # The weird way you have to set PATH in Circle 2.0
      - run: echo 'export PATH=$HOME/.local/bin:$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV

      # Use the Gruntwork Installer to install the gruntwork-module-circleci-helpers
      - run: curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.21
      - run: gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "v0.13.3"
      - run: gruntwork-install --module-name "build-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "v0.13.3"
      - run: gruntwork-install --module-name "aws-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "v0.13.3"
      - run: configure-environment-for-gruntwork-module --circle-ci-2-machine-executor --go-src-path test --use-go-dep --terraform-version NONE --terragrunt-version NONE --glide-version NONE

      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-ubuntu"
      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-amazon-linux"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - test
          # Publish new AMIs whenever a new vesion (e.g., v0.3.4) is released
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
