defaults: &defaults
  machine: true
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.21
    TERRATEST_LOG_PARSER_VERSION: v0.13.13
    MODULE_CI_VERSION: v0.13.14
    TERRAFORM_VERSION: 0.12.3
    TERRAGRUNT_VERSION: NONE
    PACKER_VERSION: 1.3.2
    GOLANG_VERSION: 1.11.2

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    configure-environment-for-gruntwork-module \
      --circle-ci-2-machine-executor \
      --terraform-version ${TERRAFORM_VERSION} \
      --terragrunt-version ${TERRAGRUNT_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --use-go-dep \
      --go-version ${GOLANG_VERSION} \
      --go-src-path test

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dep-v1-{{ checksum "test/Gopkg.lock" }}

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - save_cache:
          key: dep-v1-{{ checksum "test/Gopkg.lock" }}
          paths:
            - ./test/vendor

      # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
      # execute automatically every time before you commit, ensuring the build never fails at this step!
      - run: pip install pre-commit==1.11.2
      - run: pre-commit install
      - run: pre-commit run --all-files

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - terraform
            - packer

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - checkout
      - run: echo 'export PATH=$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV
      - run:
          <<: *install_gruntwork_utils

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/logs
            # run the tests
            run-go-tests --path test --timeout 60m | tee /tmp/logs/all.log
          no_output_timeout: 3600s
      - run:
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

  release:
    <<: *defaults
    steps:
      - checkout

      # The weird way you have to set PATH in Circle 2.0
      - run: echo 'export PATH=$HOME/.local/bin:$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-ubuntu"
      - run: ~/project/.circleci/publish-amis.sh "influxdb-ami-amazon-linux"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          # Publish new AMIs whenever a new vesion (e.g., v0.3.4) is released
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
